### ISSUE TITLE
Missing waybar-colors.css

### ISSUE THREAD

**Issue by JaKooLit** [InioX/matugen-themes#8]
As per title, I believe you forgot to add waybar-colors.css ?

![Screenshot_29-Aug_09-57-07_31922](https://github.com/user-attachments/assets/0b05b845-e4a5-48c9-9ba8-4772790e28e4)

![Screenshot_29-Aug_09-57-23_29092](https://github.com/user-attachments/assets/abe7f9df-8894-450f-bc70-62da54b29c5f)

**Comment by Heus-Sueh** [comment]
I think I forgot to put the correct name, for now you can use colors.css from the templates folder and import it into style.css
